services:
  - type: web
    name: nuoh-bot
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 5000
